routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/
Route::get('/', function () {
    return redirect(env('LANDING_URL'));
});
/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');


        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
    });
});

app/Models/Team.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    public $table = "teams";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        'user_id',
        'name',
    ];

    public static $rules = [
        'name' => 'required|unique:teams'
    ];

    public function members()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Gate;
use Illuminate\Http\Request;
use App\Services\TeamService;
use App\Http\Requests\TeamCreateRequest;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserInviteRequest;
use App\Http\Requests\TeamUpdateRequest;

class TeamController extends Controller
{
    public function __construct(TeamService $teamService)
    {
        $this->service = $teamService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $teams = $this->service->paginated($request->user()->id);
        return view('team.index')->with('teams', $teams);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $teams = $this->service->search($request->user()->id, $request->search);
        return view('team.index')->with('teams', $teams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\TeamCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeamCreateRequest $request)
    {
        $result = $this->service->create(Auth::id(), $request->except('_token'));

        if ($result) {
            return redirect('teams/'.$result->id.'/edit')->with('message', 'Successfully created');
        }

        return redirect('teams')->with('message', 'Failed to create');
    }

    /**
     * Display the specified team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showByName($name)
    {
        $team = $this->service->findByName($name);

        if (Gate::allows('team-member', [$team, Auth::user()])) {
            return view('team.show')->with('team', $team);
        }

        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $team = $this->service->find($id);
        return view('team.edit')->with('team', $team);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TeamUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy(Auth::user(), $id);

        if ($result) {
            return redirect('teams')->with('message', 'Successfully deleted');
        }

        return redirect('teams')->with('message', 'Failed to delete');
    }

    /**
     * Invite a team member
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function inviteMember(UserInviteRequest $request, $id)
    {
        $result = $this->service->invite(Auth::user(), $id, $request->email);

        if ($result) {
            return back()->with('message', 'Successfully invited member');
        }

        return back()->with('message', 'Failed to invite member - they may already be a member');
    }

    /**
     * Remove a team member
     *
     * @param  int  $userId
     * @return \Illuminate\Http\Response
     */
    public function removeMember($id, $userId)
    {
        $result = $this->service->remove(Auth::user(), $id, $userId);

        if ($result) {
            return back()->with('message', 'Successfully removed member');
        }

        return back()->with('message', 'Failed to remove member');
    }
}

resources/views/team/create.blade.php
@include('partials.message')

<div class="container">

    <form method="post" action="{{ route('teams.store') }}">
        {!! csrf_field() !!}

        @form_maker_table("teams", ['name' => 'string'])

        <a href="{{ URL::previous() }}">Cancel</a>
        <button type="submit">Create</button>

    </form>

</div>

resources/views/team/edit.blade.php
@include('partials.message')

<div class="">
    <form method="post" action="{{ url('teams/'.$team->id) }}">
        {!! csrf_field() !!}
        {!! method_field('PATCH') !!}

        @form_maker_object($team, ['name' => 'string'])

        <a href="{{ URL::previous() }}">Cancel</a>
        <button type="submit">Create</button>

    </form>
</div>

@if (Auth::user()->isTeamAdmin($team->id))

<div class="">
    <p>Invite Member</p>
    <form method="post" action="{{ url('teams/'.$team->id.'/invite') }}">
        {!! csrf_field() !!}
        <input type="email" name="email" placeholder="Email">
        <button type="submit">Create</button>
    </form>
</div>

<div class="">
    <h2>Members</h2>
    <table>
        <thead>
            <th>Name</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach($team->members as $member)
                <tr>
                    <td>{{ $member->name }}</td>
                    <td>
                        @if (! $member->isTeamAdmin($team->id))
                            <a href="{{ url('teams/'.$team->id.'/remove/'.$member->id) }}" onclick="return confirm('Are you sure you want to remove this member?')">Remove</a>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

@endif

<a href="/dashboard">Dashboard</a>

resources/views/team/index.blade.php
<div class="">

    @include('partials.message')

    <div class="">
        <div>
            <form id="" method="post" action="/teams/search">
                {!! csrf_field() !!}
                <input class="form-control" name="search" placeholder="Search">
            </form>
        </div>
        <a href="{!! route('teams.create') !!}">Add New</a>
        <h1>Teams</h1>
    </div>

    <div class="">
        @if($teams->isEmpty())
            <div>No teams found.</div>
        @else
            <table>
                <thead>
                    <th>Name</th>
                    <th width="50px">Action</th>
                </thead>
                <tbody>
                    @foreach($teams as $team)
                        <tr>
                            <td>{{ $team->name }}</td>
                            <td>
                                <a href="{!! route('teams.edit', [$team->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                <form method="post" action="{!! url('teams/'.$team->id) !!}">
                                    {!! csrf_field() !!}
                                    {!! method_field('DELETE') !!}
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete this team?')"><i class="fa fa-trash"></i> Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="row">
                {!! $teams; !!}
            </div>
        @endif
    </div>
</div>

<a href="/dashboard">Dashboard</a>

resources/views/team/show.blade.php
<div class="container">

    {{ $team->name }}

    <h2>Members</h2>
    <table>
        <thead>
            <th>Name</th>
        </thead>
        <tbody>
            @foreach($team->members as $member)
                <tr>
                    <td>{{ $member->name }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</div>